Output ./assets/demo.gif

Require termpicker

Set FontSize 18
Set Width 800
Set Height 480

Set Margin 15
# Set MarginFill "#674EFF"
Set MarginFill "#6F4624"
Set BorderRadius 10

Type "termpicker"
Enter
Sleep 250ms
Type "jlllljjhhhhh"
Sleep 1s

Tab
Sleep 500ms
Type "jlllhjlllljhhhlllhkklkl"

Tab
Sleep 500ms
Type "jkllllljhhklhkhh"
Sleep 1s

Tab
Sleep 500ms
Type "jklllllljhhklhkhh"
Sleep 1s

Type "q"
Sleep 250ms
