Output ./assets/demo.gif

Require termpicker

Set Framerate 60
Set Width 850
Set Height 600

Set FontSize 18
Set Margin 15
Set MarginFill "#6F4624"
Set BorderRadius 10

Type "termpicker"
Enter
Sleep 250ms
Type "jlllljjhhhhh"
Sleep 1s

Tab
Sleep 500ms
Type "jlllhjlllljhhhlllhkklkl"

Type "i"
Sleep 300ms
Type "#b7416e"
Enter
Sleep 500ms

Tab 2
Sleep 500ms
Type "jkllllljhhklhkhh"
Sleep 1s

Type "?"
Sleep 700ms
Type "?"

Tab
Sleep 500ms
Type "jklllllljhhklhkhh"
Sleep 1s

Type "q"
Sleep 250ms
