Output ./assets/demo.gif

Require termpicker

Set FontSize 18
Set Width 850
Set Height 600

Set Margin 15
Set MarginFill "#6F4624"
Set BorderRadius 10

Type "termpicker"
Enter
Sleep 250ms
Type "jlllljjhhhhh"
Sleep 200ms
Type "x"
Sleep 200ms
Type "s"
Sleep 1s

Tab
Sleep 500ms
Type "jlllhjlllljhhhlllhkklkl"

Tab
Sleep 500ms
Type "jkllllljhhklhkhh"
Sleep 1s

Type "?"
Sleep 500ms

Tab
Sleep 500ms
Type "jklllllljhhklhkhh"
Sleep 1s

Type "q"
Sleep 250ms
