---
name: Publish to the AUR
on:
  workflow_dispatch:  # Manual trigger via GitHub UI
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set environment variables
        id: set-vars
        run: |
          echo "PKG_NAME=$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
          echo "PKG_REPO_URI=https://github.com/${GITHUB_REPOSITORY}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          docker build -t aur-publisher ./releases/aur
      - name: Run the Docker container
        env:
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
          AUR_PUBLIC_KEY: ${{ secrets.AUR_PUBLIC_KEY }}
          PKG_REPO_URI: ${{ env.PKG_REPO_URI }}
          PKG_NAME: ${{ env.PKG_NAME }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |-
          docker run --rm \
            -e AUR_PRIVATE_KEY=$AUR_PRIVATE_KEY \
            -e AUR_PUBLIC_KEY=$AUR_PUBLIC_KEY \
            -e PKG_REPO_URI=$PKG_REPO_URI \
            -e PKG_NAME=$PKG_NAME \
            -e GIT_USER=$GIT_USER \
            aur-publisher
